services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: fermento-portainer
    restart: always
    ports:
      - "9443:9443" # HTTPS UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  cloudbeaver_data:
