[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fermento-embedded-schemas"
version = "0.1.0"
description = "Shared Pydantic schemas for Fermento embedded"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
]

[tool.setuptools.packages.find]
where = ["."]
